"""Markdown inventory generation from the live platform-profile registry."""

from __future__ import annotations

from retropal.palettes import get_palette_info
from retropal.palettes.profiles import iter_platform_profiles


def inventory_markdown() -> str:
    lines = [
        "# Palette inventory",
        "",
        "<!-- Generated by scripts/generate_palette_inventory.py; do not edit manually. -->",
        "",
        "| Platform | Profile | Palette ID | Colours | Manufacturer | Year |",
        "|---|---|---|---:|---|---:|",
    ]
    for profile in iter_platform_profiles():
        for palette_id in profile.palette_ids:
            info = get_palette_info(palette_id)
            cells = (
                profile.platform,
                profile.name,
                palette_id,
                str(info.color_count),
                info.manufacturer,
                str(info.year),
            )
            lines.append("| " + " | ".join(cell.replace("|", "\\|") for cell in cells) + " |")
    return "\n".join(lines) + "\n"
